bit:
  hamming:
  - base_args: [euclidean, hnsw]
    constructor: NmslibReuseIndex
    disabled: true
    docker_tag: ann-benchmarks-nmslib
    module: ann_benchmarks.algorithms.nmslib
    name: hnsw(nmslib)
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 800, post: 0}, false]
        args: {}
        query_args: [[1, 2, 5, 10, 15, 20, 30, 40, 50, 70, 80]]
      M-20:
        arg_groups: [{M: 20, efConstruction: 800, post: 0}, false]
        args: {}
        query_args: [[2, 5, 10, 15, 20, 30, 40, 50, 70, 80]]
      M-32:
        arg_groups: [{M: 32, efConstruction: 800, post: 2}, false]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 200,
            300, 400, 600, 700, 800, 1000, 1200, 1400, 1600, 2000]]
      M-48:
        arg_groups: [{M: 48, efConstruction: 800, post: 2}, false]
        args: {}
        query_args: [[50, 70, 90, 120, 160, 200, 400, 600, 700, 800, 1000, 1400, 1600,
            2000]]
  jaccard:
  - base_args: ['@metric', hnsw]
    constructor: NmslibReuseIndex
    disabled: false
    docker_tag: ann-benchmarks-nmslib
    module: ann_benchmarks.algorithms.nmslib
    name: hnsw(nmslib)
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 800, post: 0}, false]
        args: {}
        query_args: [[1, 2, 5, 10, 15, 20, 30, 40, 50, 70, 80]]
      M-20:
        arg_groups: [{M: 20, efConstruction: 800, post: 0}, false]
        args: {}
        query_args: [[2, 5, 10, 15, 20, 30, 40, 50, 70, 80]]
      M-32:
        arg_groups: [{M: 32, efConstruction: 800, post: 2}, false]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 200,
            300, 400, 600, 700, 800, 1000, 1200, 1400, 1600, 2000]]
      M-48:
        arg_groups: [{M: 48, efConstruction: 800, post: 2}, false]
        args: {}
        query_args: [[50, 70, 90, 120, 160, 200, 400, 600, 700, 800, 1000, 1400, 1600,
            2000]]
float:
  angular:
  - base_args: ['@metric', hnsw]
    constructor: NmslibReuseIndex
    disabled: false
    docker_tag: ann-benchmarks-nmslib
    module: ann_benchmarks.algorithms.nmslib
    name: hnsw(nmslib)
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 800, post: 0}, false]
        args: {}
        query_args: [[1, 2, 5, 10, 15, 20, 30, 40, 50, 70, 80]]
      M-20:
        arg_groups: [{M: 20, efConstruction: 800, post: 0}, false]
        args: {}
        query_args: [[2, 5, 10, 15, 20, 30, 40, 50, 70, 80]]
      M-32:
        arg_groups: [{M: 32, efConstruction: 800, post: 2}, false]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 200,
            300, 400, 600, 700, 800, 1000, 1200, 1400, 1600, 2000]]
      M-48:
        arg_groups: [{M: 48, efConstruction: 800, post: 2}, false]
        args: {}
        query_args: [[50, 70, 90, 120, 160, 200, 400, 600, 700, 800, 1000, 1400, 1600,
            2000]
euclidean:
  - base_args: ['@metric', hnsw]
    constructor: NmslibReuseIndex
    disabled: false
    docker_tag: ann-benchmarks-nmslib
    module: ann_benchmarks.algorithms.nmslib
    name: hnsw(nmslib)
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 400, post: 0}, false]
        args: {}
        query_args: [[1, 2, 5, 10, 15, 20, 30, 40, 50, 70, 80, 120]]
      M-20:
        arg_groups: [{M: 20, efConstruction: 400, post: 2}, false]
        args: {}
        query_args: [[2, 5, 10, 15, 20, 30, 40, 50, 70, 80, 120, 200, 400]]
      M-32:
        arg_groups: [{M: 32, efConstruction: 400, post: 2}, false]
        args: {}
        query_args: [[20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 200, 300,
            400]]
      M-4:
        arg_groups: [{M: 4, efConstruction: 400, post: 0}, false]
        args: {}
        query_args: [[1, 2, 5, 10, 20, 30, 50, 70, 90, 120]]
      M-8:
        arg_groups: [{M: 8, efConstruction: 400, post: 0}, false]
        args: {}
        query_args: [[1, 2, 5, 10, 20, 30, 50, 70, 90, 120, 160]]